In [30]:
import numpy as np

R = np.array([[1,0,0,1],[0,-1,0,2],[0,0,-1,10],[0,0,0,1]])
O_world = np.array([[-0.5,1.5,9,1]]).T

O_camera = R@O_world
print(O_camera)

k = np.array([[640,0,640],[0,480,480],[0,0,1]])
O_image = k @ O_camera[:-1]

print(O_image)

O_pixel = O_image/O_image[2]
print(O_pixel)

[[0.5]
 [0.5]
 [1. ]
 [1. ]]
[[960.]
 [720.]
 [  1.]]
[[960.]
 [720.]
 [  1.]]
